### ISSUE TITLE
Customer CUDA operation compilation

### ISSUE THREAD

**Issue by jshi31** [soCzech/LookForTheChange#3]
I try to compile the CUDA op with CUDA10.2 + pytorch1.11, however it reports error. Just notice in the README that the CUDA op can support at the highest CUDA8? And how to compile it with a higher CUDA version?

**Comment by soCzech** [comment]
Did you try to build the docker image?
If you are compiling it localy (i.e. not in the provided docker image), your issue probably relates to your broken build environment setup and it is unrelated to this project.

The docker image consideres compilation for certain cuda architectures (`TORCH_CUDA_ARCH_LIST="6.1;7.0;7.5;8.0"`).
Cuda architecture is NOT cuda version. The cuda version of the provided docker image is 11.0.

Given the fact you do not know the difference between the architecture and cuda version, I strongly recomend to build it only inside the docker image. Otherwise, if you need any help, you need to provide more information than 2 sentences.

Best,
Tomas

**Comment by jshi31** [comment]
I find that cuda11.6 + pytorch1.12 can successfully compile it. Thanks
