### ISSUE TITLE
Action (state) precision calculation

### ISSUE THREAD

**Issue by zihuixue** [soCzech/LookForTheChange#6]
Thank you for your work and sharing the code! I have one question about the evaluation. 

From method/utils.py L39-L61, it seems that the calculation of action precision and state precision are based on one frame only -- by taking the argmax of `pred_action`, and check whether the annotation for that frame is `action`. 

I expect the action precision would be calculated by first finding all frames where`pred_action` > 0.5, and checking how many frames has annotation = 3 (action). 

May I know the motivation for just choosing 1 frame as the evaluation? For some categories with only a few (<10) test videos available, using one frame per video seems to bring many flutuations in the numbers.

**Comment by soCzech** [comment]
Yes, you are correct. The precision is measured for one frame only.
There are several reasons.

1. Related work (https://arxiv.org/abs/1702.02738) does it like that.
2. By definition of the task, there is only one occurrence of the action in the video (though this is not always true since those are in-the-wild videos).
3. We focus on localization, not precise segmentation. Since there is (usually, see 2.) only one action per video, the detected instance is usually the only instance of action in the video.
4. The motivation of this work is that manually segmenting what action is and is not is very ambiguous. We want the model to discover what action is on its own. Such a definition may not 100% align with what the human annotators did. Selecting only a single frame (note that the frames are downsampled to 1fps) allows some slack for the model to discover anything closely resembling the action.
5. The threshold of 0.5 is arbitrary. Why not choose 0.6 or 0.4? Why not choose the best threshold given a validation set? Well, we do not have a validation set; thus, we refrain from doing this.

Hopefully, this gives you some idea why we did it like that:)
